export const mockLeads = [
  {
    id: '1',
    name: 'Sarah Johnson',
    type: 'Guaranteed',
    location: {
      street: '123 Main St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94105',
    },
    loanAmount: '$450,000',
    currentRate: '4.5',
    status: 'new',
    timeLeft: '2h 15m',
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    creditScore: '720-740',
    dti: '35%',
    propertyType: 'Single Family',
    submittedDate: new Date(Date.now() - 24 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Single Family',
      bedrooms: 3,
      bathrooms: 2,
      yearBuilt: 2010,
    },
    purpose: 'Purchase',
    region: 'west',
    state: 'CA',
    isHighValue: true,
  },
  {
    id: '2',
    name: 'Michael Chen',
    type: 'Competitive',
    location: {
      street: '456 Oak Ave',
      city: 'Seattle',
      state: 'WA',
      zip: '98101',
    },
    loanAmount: '$325,000',
    currentRate: '5.2',
    status: 'bidding',
    timeLeft: '45m',
    expiryTime: new Date(Date.now() + 45 * 60 * 1000),
    creditScore: '680-700',
    dti: '42%',
    propertyType: 'Condo',
    submittedDate: new Date(Date.now() - 12 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Condo',
      bedrooms: 2,
      bathrooms: 2,
      yearBuilt: 2015,
    },
    purpose: 'Refinance',
    region: 'west',
    state: 'WA',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    type: 'Guaranteed',
    location: {
      street: '789 Pine St',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90012',
    },
    loanAmount: '$550,000',
    currentRate: '4.8',
    status: 'new',
    timeLeft: '1h 30m',
    expiryTime: new Date(Date.now() + 90 * 60 * 1000),
    creditScore: '740-760',
    dti: '28%',
    propertyType: 'Single Family',
    submittedDate: new Date(Date.now() - 8 * 60 * 60 * 1000),
    loanTerm: '15-year',
    propertyDetails: {
      type: 'Single Family',
      bedrooms: 4,
      bathrooms: 3,
      yearBuilt: 2005,
    },
    purpose: 'Purchase',
    region: 'west',
    state: 'CA',
    isHighValue: true,
  },
  {
    id: '4',
    name: 'David Thompson',
    type: 'Competitive',
    location: {
      street: '321 Maple Dr',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
    },
    loanAmount: '$275,000',
    currentRate: '5.5',
    status: 'bidding',
    timeLeft: '15m',
    expiryTime: new Date(Date.now() + 15 * 60 * 1000),
    creditScore: '640-660',
    dti: '45%',
    propertyType: 'Townhouse',
    submittedDate: new Date(Date.now() - 4 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Townhouse',
      bedrooms: 3,
      bathrooms: 2.5,
      yearBuilt: 2018,
    },
    purpose: 'Purchase',
    region: 'south',
    state: 'TX',
  },
  {
    id: '5',
    name: 'Jennifer Martinez',
    type: 'Guaranteed',
    location: {
      street: '567 Beach Blvd',
      city: 'Miami',
      state: 'FL',
      zip: '33139',
    },
    loanAmount: '$850,000',
    currentRate: '4.2',
    status: 'new',
    timeLeft: '3h 45m',
    expiryTime: new Date(Date.now() + 3.75 * 60 * 60 * 1000),
    creditScore: '780-800',
    dti: '22%',
    propertyType: 'Luxury Condo',
    submittedDate: new Date(Date.now() - 2 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Luxury Condo',
      bedrooms: 3,
      bathrooms: 3.5,
      yearBuilt: 2022,
    },
    purpose: 'Purchase',
    region: 'southeast',
    state: 'FL',
    isHighValue: true,
  },
  {
    id: '6',
    name: 'Robert Kim',
    type: 'Competitive',
    location: {
      street: '789 Market St',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
    },
    loanAmount: '$425,000',
    currentRate: '5.1',
    status: 'bidding',
    timeLeft: '35m',
    expiryTime: new Date(Date.now() + 35 * 60 * 1000),
    creditScore: '700-720',
    dti: '38%',
    propertyType: 'Multi-Family',
    submittedDate: new Date(Date.now() - 6 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Multi-Family',
      bedrooms: 6,
      bathrooms: 4,
      yearBuilt: 1995,
    },
    purpose: 'Investment',
    region: 'midwest',
    state: 'IL',
  },
  {
    id: '7',
    name: 'Amanda Wilson',
    type: 'Guaranteed',
    location: {
      street: '432 Park Ave',
      city: 'New York',
      state: 'NY',
      zip: '10022',
    },
    loanAmount: '$1,250,000',
    currentRate: '4.0',
    status: 'new',
    timeLeft: '4h 30m',
    expiryTime: new Date(Date.now() + 4.5 * 60 * 60 * 1000),
    creditScore: '800-850',
    dti: '18%',
    propertyType: 'Luxury Apartment',
    submittedDate: new Date(Date.now() - 1 * 60 * 60 * 1000),
    loanTerm: '15-year',
    propertyDetails: {
      type: 'Luxury Apartment',
      bedrooms: 4,
      bathrooms: 4.5,
      yearBuilt: 2021,
    },
    purpose: 'Purchase',
    region: 'northeast',
    state: 'NY',
    isHighValue: true,
  },
  {
    id: '8',
    name: 'Thomas Brown',
    type: 'Competitive',
    location: {
      street: '123 Rural Rd',
      city: 'Phoenix',
      state: 'AZ',
      zip: '85001',
    },
    loanAmount: '$225,000',
    currentRate: '5.8',
    status: 'bidding',
    timeLeft: '25m',
    expiryTime: new Date(Date.now() + 25 * 60 * 1000),
    creditScore: '620-640',
    dti: '47%',
    propertyType: 'Manufactured',
    submittedDate: new Date(Date.now() - 18 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Manufactured',
      bedrooms: 3,
      bathrooms: 2,
      yearBuilt: 2012,
    },
    purpose: 'Refinance',
    region: 'southwest',
    state: 'AZ',
  },
  {
    id: '9',
    name: 'Lisa Garcia',
    type: 'Guaranteed',
    location: {
      street: '555 Harbor Dr',
      city: 'San Diego',
      state: 'CA',
      zip: '92101',
    },
    loanAmount: '$675,000',
    currentRate: '4.3',
    status: 'new',
    timeLeft: '2h 45m',
    expiryTime: new Date(Date.now() + 2.75 * 60 * 60 * 1000),
    creditScore: '760-780',
    dti: '25%',
    propertyType: 'Waterfront Condo',
    submittedDate: new Date(Date.now() - 3 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Waterfront Condo',
      bedrooms: 2,
      bathrooms: 2.5,
      yearBuilt: 2019,
    },
    purpose: 'Purchase',
    region: 'west',
    state: 'CA',
    isHighValue: true,
  },
  {
    id: '10',
    name: 'William Taylor',
    type: 'Competitive',
    location: {
      street: '777 Mountain View',
      city: 'Denver',
      state: 'CO',
      zip: '80202',
    },
    loanAmount: '$495,000',
    currentRate: '5.4',
    status: 'bidding',
    timeLeft: '55m',
    expiryTime: new Date(Date.now() + 55 * 60 * 1000),
    creditScore: '660-680',
    dti: '43%',
    propertyType: 'Mountain Cabin',
    submittedDate: new Date(Date.now() - 9 * 60 * 60 * 1000),
    loanTerm: '30-year',
    propertyDetails: {
      type: 'Mountain Cabin',
      bedrooms: 3,
      bathrooms: 2,
      yearBuilt: 2008,
    },
    purpose: 'Second Home',
    region: 'west',
    state: 'CO',
  }
];